import { Storefront } from '@mui/icons-material'

export const sidebar = [
  { title: 'Store', route: '/store', icon: <Storefront /> },
  { title: 'SKU', route: '/sku', icon: <Storefront /> },
  { title: 'Planning', route: '/planning', icon: <Storefront /> },
  { title: 'Charts', route: '/chart', icon: <Storefront /> },
]

export interface Store {
  seqNo: number
  id: string
  label: string
  city: string
  state: string
}
export interface SKU {
  ID: string
  Label: string
  Class: string
  Department: string
  Price: number
  Cost: number
}

export const initialStores: Store[] = [
  {
    seqNo: 1,
    id: 'ST035',
    label: 'San Francisco Bay Trends',
    city: 'San Francisco',
    state: 'CA',
  },
  {
    seqNo: 2,
    id: 'ST046',
    label: 'Phoenix Sunwear',
    city: 'Phoenix',
    state: 'AZ',
  },
  {
    seqNo: 3,
    id: 'ST064',
    label: 'Dallas Ranch Supply',
    city: 'Dallas',
    state: 'TX',
  },
  {
    seqNo: 4,
    id: 'ST066',
    label: 'Atlanta Outfitters',
    city: 'Atlanta',
    state: 'GA',
  },
  {
    seqNo: 5,
    id: 'ST073',
    label: 'Nashville Melody Music Store',
    city: 'Nashville',
    state: 'TN',
  },
  {
    seqNo: 6,
    id: 'ST074',
    label: 'New York Empire Eats',
    city: 'New York',
    state: 'NY',
  },
  {
    seqNo: 7,
    id: 'ST091',
    label: 'Denver Peaks Outdoor',
    city: 'Denver',
    state: 'CO',
  },
  {
    seqNo: 8,
    id: 'ST094',
    label: 'Philadelphia Liberty Market',
    city: 'Philadelphia',
    state: 'PA',
  },
  {
    seqNo: 9,
    id: 'ST097',
    label: 'Boston Harbor Books',
    city: 'Boston',
    state: 'MA',
  },
  {
    seqNo: 10,
    id: 'ST101',
    label: 'Austin Vibe Co.',
    city: 'Austin',
    state: 'TX',
  },
  {
    seqNo: 11,
    id: 'ST131',
    label: 'Los Angeles Luxe',
    city: 'Los Angeles',
    state: 'CA',
  },
  {
    seqNo: 12,
    id: 'ST150',
    label: 'Houston Harvest Market',
    city: 'Houston',
    state: 'TX',
  },
  {
    seqNo: 13,
    id: 'ST151',
    label: 'Portland Evergreen Goods',
    city: 'Portland',
    state: 'OR',
  },
  {
    seqNo: 14,
    id: 'ST156',
    label: 'Chicago Charm Boutique',
    city: 'Chicago',
    state: 'IL',
  },
  {
    seqNo: 15,
    id: 'ST163',
    label: 'Las Vegas Neon Treasures',
    city: 'Las Vegas',
    state: 'NV',
  },
  {
    seqNo: 16,
    id: 'ST175',
    label: 'Seattle Skyline Goods',
    city: 'Seattle',
    state: 'WA',
  },
  {
    seqNo: 17,
    id: 'ST176',
    label: 'Miami Breeze Apparel',
    city: 'Miami',
    state: 'FL',
  },
  {
    seqNo: 18,
    id: 'ST177',
    label: 'San Diego Wave Surf Shop',
    city: 'San Diego',
    state: 'CA',
  },
  {
    seqNo: 19,
    id: 'ST193',
    label: 'Charlotte Queen’s Closet',
    city: 'Charlotte',
    state: 'NC',
  },
  {
    seqNo: 20,
    id: 'ST208',
    label: 'Detroit Motor Gear',
    city: 'Detroit',
    state: 'MI',
  },
]
export const initialSKUs: SKU[] = [
  {
    ID: 'SK00158',
    Label: 'Crew Neck Merino Wool Sweater',
    Class: 'Tops',
    Department: "Men's Apparel",
    Price: 114.99,
    Cost: 18.28,
  },
  {
    ID: 'SK00269',
    Label: 'Faux Leather Leggings',
    Class: 'Jewelry',
    Department: 'Footwear',
    Price: 9.99,
    Cost: 8.45,
  },
  {
    ID: 'SK00300',
    Label: 'Fleece-Lined Parka',
    Class: 'Jewelry',
    Department: 'Unisex Accessories',
    Price: 199.99,
    Cost: 17.8,
  },
  {
    ID: 'SK00304',
    Label: 'Cotton Polo Shirt',
    Class: 'Tops',
    Department: "Women's Apparel",
    Price: 139.99,
    Cost: 10,
  },
]

export const calenderData = [
  {
    seqNo: 1,
    week: 'W01',
    weekLabel: 'Week 01',
    month: 'M01',
    monthLabel: 'Feb',
  },
  {
    seqNo: 2,
    week: 'W02',
    weekLabel: 'Week 02',
    month: 'M01',
    monthLabel: 'Feb',
  },
  {
    seqNo: 3,
    week: 'W03',
    weekLabel: 'Week 03',
    month: 'M01',
    monthLabel: 'Feb',
  },
  {
    seqNo: 4,
    week: 'W04',
    weekLabel: 'Week 04',
    month: 'M01',
    monthLabel: 'Feb',
  },
  {
    seqNo: 5,
    week: 'W05',
    weekLabel: 'Week 05',
    month: 'M02',
    monthLabel: 'Mar',
  },
  {
    seqNo: 6,
    week: 'W06',
    weekLabel: 'Week 06',
    month: 'M02',
    monthLabel: 'Mar',
  },
  {
    seqNo: 7,
    week: 'W07',
    weekLabel: 'Week 07',
    month: 'M02',
    monthLabel: 'Mar',
  },
  {
    seqNo: 8,
    week: 'W08',
    weekLabel: 'Week 08',
    month: 'M02',
    monthLabel: 'Mar',
  },
  {
    seqNo: 9,
    week: 'W09',
    weekLabel: 'Week 09',
    month: 'M02',
    monthLabel: 'Mar',
  },
  {
    seqNo: 10,
    week: 'W10',
    weekLabel: 'Week 10',
    month: 'M03',
    monthLabel: 'Apr',
  },
  {
    seqNo: 11,
    week: 'W11',
    weekLabel: 'Week 11',
    month: 'M03',
    monthLabel: 'Apr',
  },
  {
    seqNo: 12,
    week: 'W12',
    weekLabel: 'Week 12',
    month: 'M03',
    monthLabel: 'Apr',
  },
  {
    seqNo: 13,
    week: 'W13',
    weekLabel: 'Week 13',
    month: 'M03',
    monthLabel: 'Apr',
  },
  {
    seqNo: 14,
    week: 'W14',
    weekLabel: 'Week 14',
    month: 'M04',
    monthLabel: 'May',
  },
  {
    seqNo: 15,
    week: 'W15',
    weekLabel: 'Week 15',
    month: 'M04',
    monthLabel: 'May',
  },
  {
    seqNo: 16,
    week: 'W16',
    weekLabel: 'Week 16',
    month: 'M04',
    monthLabel: 'May',
  },
  {
    seqNo: 17,
    week: 'W17',
    weekLabel: 'Week 17',
    month: 'M04',
    monthLabel: 'May',
  },
  {
    seqNo: 18,
    week: 'W18',
    weekLabel: 'Week 18',
    month: 'M05',
    monthLabel: 'Jun',
  },
  {
    seqNo: 19,
    week: 'W19',
    weekLabel: 'Week 19',
    month: 'M05',
    monthLabel: 'Jun',
  },
  {
    seqNo: 20,
    week: 'W20',
    weekLabel: 'Week 20',
    month: 'M05',
    monthLabel: 'Jun',
  },
  {
    seqNo: 21,
    week: 'W21',
    weekLabel: 'Week 21',
    month: 'M05',
    monthLabel: 'Jun',
  },
  {
    seqNo: 22,
    week: 'W22',
    weekLabel: 'Week 22',
    month: 'M05',
    monthLabel: 'Jun',
  },
  {
    seqNo: 23,
    week: 'W23',
    weekLabel: 'Week 23',
    month: 'M06',
    monthLabel: 'Jul',
  },
  {
    seqNo: 24,
    week: 'W24',
    weekLabel: 'Week 24',
    month: 'M06',
    monthLabel: 'Jul',
  },
  {
    seqNo: 25,
    week: 'W25',
    weekLabel: 'Week 25',
    month: 'M06',
    monthLabel: 'Jul',
  },
  {
    seqNo: 26,
    week: 'W26',
    weekLabel: 'Week 26',
    month: 'M06',
    monthLabel: 'Jul',
  },
  {
    seqNo: 27,
    week: 'W27',
    weekLabel: 'Week 27',
    month: 'M07',
    monthLabel: 'Aug',
  },
  {
    seqNo: 28,
    week: 'W28',
    weekLabel: 'Week 28',
    month: 'M07',
    monthLabel: 'Aug',
  },
  {
    seqNo: 29,
    week: 'W29',
    weekLabel: 'Week 29',
    month: 'M07',
    monthLabel: 'Aug',
  },
  {
    seqNo: 30,
    week: 'W30',
    weekLabel: 'Week 30',
    month: 'M07',
    monthLabel: 'Aug',
  },
  {
    seqNo: 31,
    week: 'W31',
    weekLabel: 'Week 31',
    month: 'M08',
    monthLabel: 'Sep',
  },
  {
    seqNo: 32,
    week: 'W32',
    weekLabel: 'Week 32',
    month: 'M08',
    monthLabel: 'Sep',
  },
  {
    seqNo: 33,
    week: 'W33',
    weekLabel: 'Week 33',
    month: 'M08',
    monthLabel: 'Sep',
  },
  {
    seqNo: 34,
    week: 'W34',
    weekLabel: 'Week 34',
    month: 'M08',
    monthLabel: 'Sep',
  },
  {
    seqNo: 35,
    week: 'W35',
    weekLabel: 'Week 35',
    month: 'M08',
    monthLabel: 'Sep',
  },
  {
    seqNo: 36,
    week: 'W36',
    weekLabel: 'Week 36',
    month: 'M09',
    monthLabel: 'Oct',
  },
  {
    seqNo: 37,
    week: 'W37',
    weekLabel: 'Week 37',
    month: 'M09',
    monthLabel: 'Oct',
  },
  {
    seqNo: 38,
    week: 'W38',
    weekLabel: 'Week 38',
    month: 'M09',
    monthLabel: 'Oct',
  },
  {
    seqNo: 39,
    week: 'W39',
    weekLabel: 'Week 39',
    month: 'M09',
    monthLabel: 'Oct',
  },
  {
    seqNo: 40,
    week: 'W40',
    weekLabel: 'Week 40',
    month: 'M10',
    monthLabel: 'Nov',
  },
  {
    seqNo: 41,
    week: 'W41',
    weekLabel: 'Week 41',
    month: 'M10',
    monthLabel: 'Nov',
  },
  {
    seqNo: 42,
    week: 'W42',
    weekLabel: 'Week 42',
    month: 'M10',
    monthLabel: 'Nov',
  },
  {
    seqNo: 43,
    week: 'W43',
    weekLabel: 'Week 43',
    month: 'M10',
    monthLabel: 'Nov',
  },
  {
    seqNo: 44,
    week: 'W44',
    weekLabel: 'Week 44',
    month: 'M11',
    monthLabel: 'Dec',
  },
  {
    seqNo: 45,
    week: 'W45',
    weekLabel: 'Week 45',
    month: 'M11',
    monthLabel: 'Dec',
  },
  {
    seqNo: 46,
    week: 'W46',
    weekLabel: 'Week 46',
    month: 'M11',
    monthLabel: 'Dec',
  },
  {
    seqNo: 47,
    week: 'W47',
    weekLabel: 'Week 47',
    month: 'M11',
    monthLabel: 'Dec',
  },
  {
    seqNo: 48,
    week: 'W48',
    weekLabel: 'Week 48',
    month: 'M11',
    monthLabel: 'Dec',
  },
  {
    seqNo: 49,
    week: 'W49',
    weekLabel: 'Week 49',
    month: 'M12',
    monthLabel: 'Jan',
  },
  {
    seqNo: 50,
    week: 'W50',
    weekLabel: 'Week 50',
    month: 'M12',
    monthLabel: 'Jan',
  },
  {
    seqNo: 51,
    week: 'W51',
    weekLabel: 'Week 51',
    month: 'M12',
    monthLabel: 'Jan',
  },
  {
    seqNo: 52,
    week: 'W52',
    weekLabel: 'Week 52',
    month: 'M12',
    monthLabel: 'Jan',
  },
]
export const planningData = [
  { Store: 'ST035', SKU: 'SK00158', Week: 'W01', 'Sales Units': 58 },
  { Store: 'ST035', SKU: 'SK00158', Week: 'W07', 'Sales Units': 107 },
  { Store: 'ST035', SKU: 'SK00158', Week: 'W09', 'Sales Units': 0 },
  { Store: 'ST035', SKU: 'SK00158', Week: 'W11', 'Sales Units': 92 },
  { Store: 'ST035', SKU: 'SK00158', Week: 'W13', 'Sales Units': 122 },
  { Store: 'ST035', SKU: 'SK00158', Week: 'W15', 'Sales Units': 38 },
  { Store: 'ST035', SKU: 'SK00158', Week: 'W23', 'Sales Units': 88 },
  { Store: 'ST035', SKU: 'SK00158', Week: 'W31', 'Sales Units': 45 },
  { Store: 'ST035', SKU: 'SK00158', Week: 'W35', 'Sales Units': 197 },
  { Store: 'ST035', SKU: 'SK00158', Week: 'W50', 'Sales Units': 133 },
  { Store: 'ST035', SKU: 'SK00269', Week: 'W05', 'Sales Units': 107 },
  { Store: 'ST035', SKU: 'SK00269', Week: 'W06', 'Sales Units': 104 },
  { Store: 'ST035', SKU: 'SK00269', Week: 'W09', 'Sales Units': 32 },
  { Store: 'ST035', SKU: 'SK00269', Week: 'W18', 'Sales Units': 174 },
  { Store: 'ST035', SKU: 'SK00269', Week: 'W23', 'Sales Units': 174 },
  { Store: 'ST035', SKU: 'SK00269', Week: 'W27', 'Sales Units': 37 },
  { Store: 'ST035', SKU: 'SK00269', Week: 'W28', 'Sales Units': 95 },
  { Store: 'ST035', SKU: 'SK00269', Week: 'W29', 'Sales Units': 161 },
  { Store: 'ST035', SKU: 'SK00269', Week: 'W30', 'Sales Units': 175 },
  { Store: 'ST035', SKU: 'SK00269', Week: 'W32', 'Sales Units': 200 },
  { Store: 'ST035', SKU: 'SK00269', Week: 'W33', 'Sales Units': 120 },
  { Store: 'ST035', SKU: 'SK00269', Week: 'W51', 'Sales Units': 167 },
  { Store: 'ST035', SKU: 'SK00300', Week: 'W14', 'Sales Units': 135 },
  { Store: 'ST035', SKU: 'SK00300', Week: 'W15', 'Sales Units': 42 },
  { Store: 'ST035', SKU: 'SK00300', Week: 'W41', 'Sales Units': 185 },
  { Store: 'ST035', SKU: 'SK00300', Week: 'W46', 'Sales Units': 38 },
  { Store: 'ST035', SKU: 'SK00300', Week: 'W50', 'Sales Units': 149 },
  { Store: 'ST035', SKU: 'SK00304', Week: 'W16', 'Sales Units': 40 },
  { Store: 'ST035', SKU: 'SK00304', Week: 'W18', 'Sales Units': 140 },
  { Store: 'ST035', SKU: 'SK00304', Week: 'W19', 'Sales Units': 200 },
  { Store: 'ST035', SKU: 'SK00304', Week: 'W23', 'Sales Units': 108 },
  { Store: 'ST035', SKU: 'SK00304', Week: 'W36', 'Sales Units': 28 },
  { Store: 'ST035', SKU: 'SK00304', Week: 'W42', 'Sales Units': 11 },
  { Store: 'ST035', SKU: 'SK00304', Week: 'W47', 'Sales Units': 42 },
  { Store: 'ST035', SKU: 'SK00766', Week: 'W04', 'Sales Units': 167 },
  { Store: 'ST035', SKU: 'SK00766', Week: 'W08', 'Sales Units': 143 },
  { Store: 'ST035', SKU: 'SK00766', Week: 'W10', 'Sales Units': 120 },
  { Store: 'ST035', SKU: 'SK00766', Week: 'W12', 'Sales Units': 21 },
  { Store: 'ST035', SKU: 'SK00766', Week: 'W13', 'Sales Units': 92 },
  { Store: 'ST035', SKU: 'SK00766', Week: 'W14', 'Sales Units': 141 },
  { Store: 'ST035', SKU: 'SK00766', Week: 'W15', 'Sales Units': 108 },
  { Store: 'ST035', SKU: 'SK00766', Week: 'W19', 'Sales Units': 167 },
  { Store: 'ST035', SKU: 'SK00766', Week: 'W21', 'Sales Units': 1 },
  { Store: 'ST035', SKU: 'SK00766', Week: 'W42', 'Sales Units': 63 },
  { Store: 'ST035', SKU: 'SK00766', Week: 'W44', 'Sales Units': 179 },
  { Store: 'ST035', SKU: 'SK00766', Week: 'W49', 'Sales Units': 110 },
  { Store: 'ST035', SKU: 'SK00786', Week: 'W02', 'Sales Units': 100 },
  { Store: 'ST035', SKU: 'SK00786', Week: 'W05', 'Sales Units': 16 },
  { Store: 'ST035', SKU: 'SK00786', Week: 'W09', 'Sales Units': 76 },
  { Store: 'ST035', SKU: 'SK00786', Week: 'W11', 'Sales Units': 66 },
  { Store: 'ST035', SKU: 'SK00786', Week: 'W13', 'Sales Units': 143 },
  { Store: 'ST035', SKU: 'SK00786', Week: 'W17', 'Sales Units': 95 },
  { Store: 'ST035', SKU: 'SK00786', Week: 'W20', 'Sales Units': 39 },
  { Store: 'ST035', SKU: 'SK00786', Week: 'W21', 'Sales Units': 6 },
  { Store: 'ST035', SKU: 'SK00786', Week: 'W29', 'Sales Units': 174 },
  { Store: 'ST035', SKU: 'SK00786', Week: 'W35', 'Sales Units': 128 },
  { Store: 'ST035', SKU: 'SK00786', Week: 'W36', 'Sales Units': 166 },
  { Store: 'ST035', SKU: 'SK00786', Week: 'W41', 'Sales Units': 185 },
  { Store: 'ST035', SKU: 'SK00786', Week: 'W43', 'Sales Units': 47 },
  { Store: 'ST035', SKU: 'SK00786', Week: 'W44', 'Sales Units': 87 },
]
